version: 2

jobs:
  build:
    docker:
      # Primary container
      - image: circleci/node:8.9.4
    steps:
      - checkout
      - restore_cache:
          key: dependencies-{{ arch }}-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: yarn && yarn add -D jest-junit
      - save_cache:
          key: dependencies-{{ arch }}-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Lint and Test
          command: |
            mkdir -p ~/reports
            yarn lint --format junit --output-file ~/reports/eslint.xml
            yarn test:coverage --ci --coverageDirectory ~/reports --testResultsProcessor jest-junit
          environment:
            JEST_JUNIT_OUTPUT: "~/reports/test-results.xml"
      - run:
          name: Send Coverage
          command: yarn run coveralls < ~/reports/lcov.info
      - store_test_results:
          path: ~/reports
      - store_artifacts:
          path: ~/reports

  deploy:
    machine:
      image: circleci/classic:edge
    environment:
      DOCKER_REPOSITORY: koa-rest-api-boilerplate
    steps:
      - checkout
      - run:
          name: Build Docker Image
          command: |
            docker info
            docker build --rm=false -t $DOCKER_REPOSITORY .
      - run:
          name: Deploy to the Production Environment
          command: echo "Deploy to Production Environment"

  deploy-dev:
    machine: true
    steps:
      - checkout
      - run:
          name: Deploy to the Development Environment
          command: echo "Deploy to Development Environment"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - deploy-dev:
          requires:
            - build
          filters:
            branches:
              only: develop
